1. Write a Python program to convert a list of numeric value into a one-dimensional
 NumPy array.
 Expected Output:
 Original List: [12.23, 13.32, 100, 36.32]
 One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [2]:
import numpy as np

In [3]:

lst=[12.23, 13.32, 100, 36.32]
arr=np.array(lst)
print(arr)

[ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [5]:
items=np.arange(2,11)
result=items.reshape(3,3)
print(result)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [9]:
vector=np.zeros(10)
vector[5]=11
print(vector)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [10]:
arr=np.arange(12,38)
result=arr[::-1]
print(result)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]

In [15]:
arr=np.ones((5,5))
arr[1:-1,1:-1]=0
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]

In [17]:
arr=np.ones((3,3))
new_arr=np.zeros((5,5))
new_arr[1:-1,1:-1]=arr
print(new_arr)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [20]:
arr=np.zeros((8,8))
arr[1::2,::2]=1
arr[::2,1::2]=1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


8. Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [23]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]
tuple = ((8, 4, 6), (1, 2, 3))
lst_array=np.array(lst)
tuple_array=np.array(tuple)
print(lst_array,'\n',tuple_array)

[1 2 3 4 5 6 7 8] 
 [[8 4 6]
 [1 2 3]]


9. Write a Python program to append values to the end of an array.
Expected Output:
Original array:
[10, 20, 30]

After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [26]:
arr=np.arange(10,40,10)
new_items=np.arange(40,100,10)
result=np.append(arr,new_items)
print(result)

[10 20 30 40 50 60 70 80 90]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]

In [28]:
arr = np.array([1 + 0j, 0.70710678 + 0.70710678j])
real_part = arr.real
imaginary_part = arr.imag

print(f"real part: {real_part}\nImaginary pary: {imaginary_part}")

real part: [1.         0.70710678]
Imaginary pary:[0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24

In [34]:
arr=np.array([1,2,3])
size=arr.size
length=arr.itemsize
total_bytes=size*length

print(f"Size of the array:{size}")
print(f"Length of one array element in bytes:{length}")
print(f"Total bytes consumed by the elements of the array:{total_bytes}")

Size of the array:3
Length of one array element in bytes:4
Total bytes consumed by the elements of the array:12


12. Write a Python program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [37]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])
common_values = np.intersect1d(array1, array2)
print(f"common values: {common_values}")

common values: [10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]

In [38]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70, 90])
difference = np.setdiff1d(array1, array2)
print(f"set difference values:{difference}")

set difference values:[ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]

In [39]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])
result = np.setxor1d(array1, array2)
print(f"Unique values that are in only one (not both) of the input arrays:{result}")

Unique values that are in only one (not both) of the input arrays:[ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]

In [41]:
a = np.array([1, 2])
b = np.array([4, 5])

greater_than = a > b
greater_than_equal = a >= b
less_than = a < b
less_than_equal = a <= b

print("a > b:", greater_than)
print("a >= b:", greater_than_equal)
print("a < b:", less_than)
print("a <= b:", less_than_equal)

a > b: [False False]
a >= b: [False False]
a < b: [ True  True]
a <= b: [ True  True]


15. Write a Python program to save a NumPy array to a text file.

In [45]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.savetxt('array.txt', array)

16. Write a Python program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]

In [44]:
array = np.array([[10, 20, 30], [20, 40, 50]])
result= array.flatten()
print(f"flattened array:{result}")

flattened array:[10 20 30 20 40 50]


17. Write a Python program to change the data type of an array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Data type of the array x is: int32
New Type: float64
[[ 2. 4. 6.]
[ 6. 8. 10.]]

In [46]:
x = np.array([[2, 4, 6], [6, 8, 10]])
result=x.astype(np.float64)
print(f"new type:{result.dtype}")

new type:float64


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]

In [47]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19. Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]

[ 1. 1. 1.]]

In [48]:
array = np.tril(np.ones((4, 3)))
print(array)

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


20. Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]]

In [51]:
array1 = np.array([[0, 1, 3], [5, 7, 9]])
array2 = np.array([[0, 2, 4], [6, 8, 10]])

result = np.concatenate((array1, array2), axis=1)
print(result)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21. Write a Python program to make an array immutable (read-only).
Expected Output:
Test the array is read-only or not:
Try to change the value of the first element:
Traceback (most recent call last):
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in
x[0] = 1
ValueError: assignment destination is read-only

In [52]:
x = np.array([1, 2, 3, 4])
x.flags.writeable = False

print("Test the array is read-only or not:")
try:
    x[0] = 10  
except ValueError as e:
    print("Error:", e)


Test the array is read-only or not:
Error: assignment destination is read-only


22. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.
Expected Output:
Original array elements:
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]]
New array elements:
[[ 0 3 6 9]
[12 15 18 21]
[24 27 30 33]]

In [53]:
array=np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11]])
new_array = array * 3
print(new_array)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[[0 1]
[2 3]
[4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]

In [54]:
array = np.array([[0, 1],[2, 3],[4, 5]])
lst = array.tolist()
print(lst)

[[0, 1], [2, 3], [4, 5]]


24. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:

Original array elements:
[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349
0.35399976 0.99469633 0.0694458 0.54711478]
Print array values with precision 3:
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]

In [55]:
array = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874,0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478])
np.set_printoptions(precision=3)
print(array)

[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


25. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.
Expected Output:
Original array elements:
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]
Print array values with precision 3:
[ 0. 1.6 1200. 0.235]

In [56]:
array = np.array([1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
np.set_printoptions(suppress=True, precision=3)
print(array)


[   0.       1.6   1200.       0.235]


26. Write a Python program to how to add an extra column to an numpy array.
Expected Output:
[[ 10 20 30 100]
[ 40 50 60 200]]

In [57]:
array = np.array([[10, 20, 30],[40, 50, 60]])
extra_column = np.array([[100],[200]])
result = np.hstack((array, extra_column))
print(result)

[[ 10  20  30 100]
 [ 40  50  60 200]]


27. Write a Python program to remove specific elements in a numpy array.
Expected Output:
Original array:
[ 10 20 30 40 50 60 70 80 90 100]
Delete first, fourth and fifth elements:
[ 20 30 60 70 80 90 100]

In [58]:
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
indices_to_delete = [0, 3, 4]
result= np.delete(array, indices_to_delete)
print(result)

[ 20  30  60  70  80  90 100]
